[toolchain]

[features]
resolution = true
skip-lint = true

[programs.localnet]
flipcash = "ccJYP5gjZqcEHaphcxAZvkxCrnTVfYMjyhSYkpQtf8Z"

[registry]
url = "https://api.apr.dev"

[provider]
wallet = "keypair-owner.json"
cluster = "http://127.0.0.1:8899"

[scripts]
test = "echo \"Error: no test specified\" && exit 1"
